apiVersion: v1
kind: Service
metadata:
  name: dice-app-service
spec:
  type: NodePort
  selector:
    app: dice-app
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30001  # NodePort can be any in the range 30000-32767