apiVersion: apps/v1
kind: Deployment
metadata:
  name: dice-app-deployment
spec:
  replicas: 7
  selector:
    matchLabels:
      app: dice-app
  template:
    metadata:
      labels:
        app: dice-app
    spec:
      containers:
      - name: dice-app 
        image: shay88/dice-app-app:v-0.0.4
        ports:
        - containerPort: 5000
        env:
          - name: MONGO_URL
            value: "mongodb://mongo-service:27017/diceApp"
          - name: REDIS_URL
            value: "redis://redis-service:6379"